# matti_add_mod / matti_embed_section - shared with tests (see tests/CMakeLists.txt).
#
# A mod is a plain ELF shared object. libmatti reads it like a jar: the ELF
# section ".matti_manifest" is the manifest and every other section whose name
# does not start with '.' is the jar entry of exactly that name.

# The ELF section libmatti exposes as "META-INF/MANIFEST.MF".
set(MATTI_MANIFEST_SECTION ".matti_manifest")

# matti_embed_section(<target> <entry-name> <file>)
#
# Embeds <file> into the ELF section <entry-name>. The array is sized exactly
# like the literal, so no terminating NUL ends up inside the section.
function(matti_embed_section target entry file)
    get_filename_component(file "${file}" ABSOLUTE)
    file(READ "${file}" content)
    string(LENGTH "${content}" length)
    if(length EQUAL 0)
        message(FATAL_ERROR "matti_embed_section(${target}): ${file} is empty")
    endif()

    string(REPLACE "\\" "\\\\" content "${content}")
    string(REPLACE "\"" "\\\"" content "${content}")
    string(REPLACE "\r" "\\r" content "${content}")
    string(REPLACE "\t" "\\t" content "${content}")
    string(REPLACE "\n" "\\n\"\n    \"" content "${content}")

    string(MAKE_C_IDENTIFIER "matti_entry_${entry}" symbol)
    set(generated "${CMAKE_CURRENT_BINARY_DIR}/${target}.${symbol}.c")
    file(WRITE "${generated}"
            "// generated by matti_embed_section from ${file}\n"
            "__attribute__((used, section(\"${entry}\")))\n"
            "const char ${symbol}[${length}] =\n    \"${content}\";\n")

    target_sources(${target} PRIVATE "${generated}")
endfunction()

# matti_add_section(<target> <entry-name> <file>)
#
# Appends <file> to the already-linked shared object <target> as the ELF
# section <entry-name> (objcopy --add-section). Use it for sections the linker
# cannot carry, for example entry names without an ELF-safe shape or content
# that only exists after the link.
function(matti_add_section target entry file)
    get_filename_component(file "${file}" ABSOLUTE)
    find_program(OBJCOPY_EXE objcopy REQUIRED)
    add_custom_command(TARGET ${target} POST_BUILD
            COMMAND ${OBJCOPY_EXE} --add-section "${entry}=${file}"
                    --set-section-flags "${entry}=contents,readonly"
                    "$<TARGET_FILE:${target}>"
            VERBATIM)
endfunction()

# matti_add_mod(<target>
#         MOD_ID <modid> MOD_VERSION <version>
#         SOURCES <file>... [RESOURCES <dir>] [MANIFEST <file>]
#         [OUTPUT_NAME <file>] [OUTPUT_DIR <dir>])
#
# Builds the mod .so. The manifest is generated from MOD_ID/MOD_VERSION unless
# MANIFEST points at a file. Every file below RESOURCES is embedded under its
# own path, so the entry name is the file path relative to RESOURCES:
#
#     resources/META-INF/services/<interface>   -> "META-INF/services/<interface>"
#     resources/assets/<modid>/lang/en_us.json  -> "assets/<modid>/lang/en_us.json"
#
# OUTPUT_NAME defaults to "<modid>-<version>" (the file FML finds in the mods
# folder), OUTPUT_DIR defaults to MATTI_MODS_DIR.
function(matti_add_mod target)
    cmake_parse_arguments(ARG "" "MOD_ID;MOD_VERSION;RESOURCES;MANIFEST;OUTPUT_NAME;OUTPUT_DIR" "SOURCES" ${ARGN})

    if(NOT ARG_MOD_ID OR NOT ARG_SOURCES)
        message(FATAL_ERROR "matti_add_mod(${target}): MOD_ID and SOURCES are required")
    endif()

    add_library(${target} SHARED ${ARG_SOURCES})
    target_include_directories(${target} PRIVATE "${MATTI_LIBRARY_DIR}")

    if(NOT ARG_OUTPUT_NAME)
        set(ARG_OUTPUT_NAME "${ARG_MOD_ID}-${ARG_MOD_VERSION}")
    endif()
    if(NOT ARG_OUTPUT_DIR)
        set(ARG_OUTPUT_DIR "${MATTI_MODS_DIR}")
    endif()

    set_target_properties(${target} PROPERTIES
            PREFIX ""
            OUTPUT_NAME "${ARG_OUTPUT_NAME}"
            LIBRARY_OUTPUT_DIRECTORY "${ARG_OUTPUT_DIR}"
    )

    if(ARG_MANIFEST)
        matti_embed_section(${target} "${MATTI_MANIFEST_SECTION}" "${ARG_MANIFEST}")
    else()
        # "FMLModType" tells the loader that the file is a mod on its own, without
        # a META-INF/neoforge.mods.toml; "Automatic-Module-Name" is the mod id
        # when the file has no mod metadata.
        set(manifest "${CMAKE_CURRENT_BINARY_DIR}/${target}.MANIFEST.MF")
        file(WRITE "${manifest}"
                "Manifest-Version: 1.0\n"
                "Automatic-Module-Name: ${ARG_MOD_ID}\n"
                "Implementation-Version: ${ARG_MOD_VERSION}\n"
                "FMLModType: MOD\n"
                "\n")
        matti_embed_section(${target} "${MATTI_MANIFEST_SECTION}" "${manifest}")
    endif()

    if(ARG_RESOURCES)
        get_filename_component(resourceRoot "${ARG_RESOURCES}" ABSOLUTE)
        file(GLOB_RECURSE resourceFiles CONFIGURE_DEPENDS RELATIVE "${resourceRoot}" "${resourceRoot}/*")
        foreach(resource IN LISTS resourceFiles)
            matti_embed_section(${target} "${resource}" "${resourceRoot}/${resource}")
        endforeach()
    endif()
endfunction()
