// Worldgen harness (P7.2): the chunk generator stack -
//   - RandomSupport/Xoroshiro/XoroshiroRandomSource: the exact Java vectors
//     (the reference values generated by the vendored vendor code paths)
//   - ImprovedNoise/PerlinNoise/NormalNoise: the seeding order + the sampled
//     values against the JVM reference run
//   - FlatLevelSource: the superflat recipe end to end (fillFromNoise over
//     the sections, the WG heightmaps, getBaseHeight/getSpawnHeight)
//   - the biome identity: the interning + the SerializableChunkData palette
//     roundtrip through the section biome

#include "libmatti/net/minecraft/Bootstrap.h"
#include "libmatti/net/minecraft/server/bootstrap/VanillaBlocks.h"
#include "libmatti/net/minecraft/util/Mth.h"
#include "libmatti/net/minecraft/world/level/Level.h"
#include "libmatti/net/minecraft/world/level/biome/Biome.h"
#include "libmatti/net/minecraft/world/level/chunk/ChunkAccess.h"
#include "libmatti/net/minecraft/world/level/chunk/ChunkGenerator.h"
#include "libmatti/net/minecraft/world/level/chunk/LevelChunk.h"
#include "libmatti/net/minecraft/world/level/chunk/LevelChunkSection.h"
#include "libmatti/net/minecraft/world/level/chunk/storage/SerializableChunkData.h"
#include "libmatti/net/minecraft/world/level/levelgen/Heightmap.h"
#include "libmatti/net/minecraft/world/level/levelgen/RandomSupport.h"
#include "libmatti/net/minecraft/world/level/levelgen/XoroshiroRandomSource.h"
#include "libmatti/net/minecraft/world/level/levelgen/Xoroshiro128PlusPlus.h"
#include "libmatti/net/minecraft/world/level/levelgen/flat/FlatLevelSource.h"
#include "libmatti/net/minecraft/world/level/levelgen/synth/ImprovedNoise.h"
#include "libmatti/net/minecraft/world/level/levelgen/synth/PerlinNoise.h"
#include "libmatti/net/minecraft/world/level/levelgen/synth/NormalNoise.h"
#include "libmatti/net/minecraft/nbt/NbtIo.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int failures;
static int checks;

static void check(int condition, const char *what)
{
    checks++;
    if (!condition)
    {
        failures++;
        printf("FAIL: %s\n", what);
    }
}

static void check_near(double value, double expected, double eps, const char *what)
{
    checks++;
    if (fabs(value - expected) > eps)
    {
        failures++;
        printf("FAIL: %s (got %.17g, want %.17g)\n", what, value, expected);
    }
}

static void check_i64(int64_t value, int64_t expected, const char *what)
{
    checks++;
    if (value != expected)
    {
        failures++;
        printf("FAIL: %s (got %lld, want %lld)\n", what, (long long) value, (long long) expected);
    }
}

// ---------------------------------------------------------------------------
// the RNG parity (the vectors from the JVM reference run, seed 12345)
// ---------------------------------------------------------------------------

static void test_rng(void)
{
    check_i64(LIBMATTI_MC_RandomSupport_MixStafford13(12345), -906084347102765743LL, "mixStafford13(12345)");
    int64_t lo, hi;
    LIBMATTI_MC_RandomSupport_UpgradeSeedTo128bit(12345, &lo, &hi);
    check_i64(lo, 733019005196230046LL, "upgradeSeedTo128bit lo");
    check_i64(hi, -3494074583369400597LL, "upgradeSeedTo128bit hi");

    LIBMATTI_MC_XoroshiroRandomSource random;
    LIBMATTI_MC_XoroshiroRandomSource_Init(&random, 12345);
    static const int64_t LONGS[8] = {-8118485274630516485LL, 8241557746459281790LL, 4143755034716878659LL,
                                     1226499899398695337LL,  -8052343703659247148LL, 3531070785145858642LL,
                                     1108557117547011729LL,  -3481306480006774438LL};
    for (int i = 0; i < 8; i++)
        check_i64(LIBMATTI_MC_XoroshiroRandomSource_NextLong(&random), LONGS[i], "nextLong sequence");

    LIBMATTI_MC_XoroshiroRandomSource bounded;
    LIBMATTI_MC_XoroshiroRandomSource_Init(&bounded, 12345);
    static const int32_t BOUNDED[10] = {1, 81, 87, 1, 55, 69, 20, 50, 29, 98};
    for (int i = 0; i < 10; i++)
        check_i64(LIBMATTI_MC_XoroshiroRandomSource_NextIntBounded(&bounded, 100), BOUNDED[i], "nextInt(100) sequence");

    LIBMATTI_MC_XoroshiroRandomSource doubles;
    LIBMATTI_MC_XoroshiroRandomSource_Init(&doubles, 12345);
    static const double DOUBLES[5] = {0.5598960189790001, 0.4467757307591437, 0.22463340556193725,
                                      0.06648869129932213, 0.5634815606464042};
    for (int i = 0; i < 5; i++)
        check_near(LIBMATTI_MC_XoroshiroRandomSource_NextDouble(&doubles), DOUBLES[i], 1e-15, "nextDouble sequence");

    LIBMATTI_MC_XoroshiroRandomSource floats;
    LIBMATTI_MC_XoroshiroRandomSource_Init(&floats, 12345);
    static const float FLOATS[5] = {0.559896f, 0.44677573f, 0.2246334f, 0.06648868f, 0.56348157f};
    for (int i = 0; i < 5; i++)
        check_near((double) LIBMATTI_MC_XoroshiroRandomSource_NextFloat(&floats), (double) FLOATS[i], 1e-9,
                   "nextFloat sequence");

    // the forkPositional state + the fromHashOf path (the octave seeds ride it)
    LIBMATTI_MC_XoroshiroRandomSource fork;
    LIBMATTI_MC_XoroshiroRandomSource_Init(&fork, 12345);
    LIBMATTI_MC_XoroshiroPositionalRandomFactory factory;
    LIBMATTI_MC_XoroshiroRandomSource_ForkPositional(&fork, &factory);
    check_i64(factory.seedLo, -8118485274630516485LL, "factory seedLo");
    check_i64(factory.seedHi, 8241557746459281790LL, "factory seedHi");

    LIBMATTI_MC_XoroshiroRandomSource hashed;
    LIBMATTI_MC_XoroshiroPositionalRandomFactory_FromHashOf(&factory, "octave_-7", &hashed);
    check_i64(LIBMATTI_MC_XoroshiroRandomSource_NextLong(&hashed), -3406988683973455730LL,
              "factory.fromHashOf(octave_-7) first nextLong");

    // the positional at() path rides Mth.getSeed
    LIBMATTI_MC_XoroshiroRandomSource at1, at2;
    LIBMATTI_MC_XoroshiroPositionalRandomFactory_At(&factory, 10, 64, -4, &at1);
    LIBMATTI_MC_XoroshiroPositionalRandomFactory_At(&factory, 10, 64, -4, &at2);
    check_i64(LIBMATTI_MC_XoroshiroRandomSource_NextLong(&at1), LIBMATTI_MC_XoroshiroRandomSource_NextLong(&at2),
              "factory.at determinism");
}

// ---------------------------------------------------------------------------
// the noise stack (the JVM reference values, seed 12345)
// ---------------------------------------------------------------------------

static void test_noise(void)
{
    LIBMATTI_MC_XoroshiroRandomSource random;
    LIBMATTI_MC_XoroshiroRandomSource_Init(&random, 12345);
    LIBMATTI_MC_ImprovedNoise noise;
    LIBMATTI_MC_ImprovedNoise_Init(&noise, &random);
    check_near(noise.xo, 143.33338085862403, 0.0, "improved xo exact");
    check_near(noise.yo, 114.37458707434078, 0.0, "improved yo exact");
    check_near(noise.zo, 57.50615182385594, 0.0, "improved zo exact");
    check_near(LIBMATTI_MC_ImprovedNoise_Noise(&noise, 1.5, -2.25, 3.75), 0.17092929742541735, 1e-15,
               "improved noise value");

    double amps[6] = {1, 1, 1, 1, 1, 1};
    LIBMATTI_MC_XoroshiroRandomSource perlinRandom;
    LIBMATTI_MC_XoroshiroRandomSource_Init(&perlinRandom, 12345);
    LIBMATTI_MC_PerlinNoise *perlin = LIBMATTI_MC_PerlinNoise_Create(&perlinRandom, -7, amps, 6);
    check(perlin != NULL, "perlin create");
    if (perlin != NULL)
    {
        check_near(LIBMATTI_MC_PerlinNoise_GetValue(perlin, 1.5, -2.25, 3.75), 0.12376282356964696, 1e-15,
                   "perlin value");
        // Java: wrap folds the scaled coordinate mod 2^25 (the float-precision
        // lattice bound) - the octave-0 scale is 2^-7, so the fold needs x past
        // 2^32 for every octave to land on the same sample
        check(LIBMATTI_MC_PerlinNoise_GetValue(perlin, 4294967296.5, 0.0, 0.0)
                  == LIBMATTI_MC_PerlinNoise_GetValue(perlin, 0.5, 0.0, 0.0),
              "perlin wrap folds the 3.3554432E7 lattice");
        LIBMATTI_MC_PerlinNoise_Free(perlin);
    }

    LIBMATTI_MC_XoroshiroRandomSource normalRandom;
    LIBMATTI_MC_XoroshiroRandomSource_Init(&normalRandom, 12345);
    LIBMATTI_MC_NormalNoise *normal = LIBMATTI_MC_NormalNoise_Create(&normalRandom, -7, amps, 6);
    check(normal != NULL, "normal create");
    if (normal != NULL)
    {
        check_near(LIBMATTI_MC_NormalNoise_GetValue(normal, 1.5, -2.25, 3.75), 0.1475020969419901, 1e-15,
                   "normal value");
        check_near(LIBMATTI_MC_NormalNoise_MaxValue(normal), 5.7142857142857136, 1e-9, "normal max bound");
        LIBMATTI_MC_NormalNoise_Free(normal);
    }

    // the noise determinism: two sources over the same seed agree
    LIBMATTI_MC_XoroshiroRandomSource a, b;
    LIBMATTI_MC_XoroshiroRandomSource_Init(&a, 987654321);
    LIBMATTI_MC_XoroshiroRandomSource_Init(&b, 987654321);
    LIBMATTI_MC_PerlinNoise *pa = LIBMATTI_MC_PerlinNoise_Create(&a, -7, amps, 6);
    LIBMATTI_MC_PerlinNoise *pb = LIBMATTI_MC_PerlinNoise_Create(&b, -7, amps, 6);
    if (pa != NULL && pb != NULL)
    {
        double va = LIBMATTI_MC_PerlinNoise_GetValue(pa, 12.75, -30.5, 44.25);
        double vb = LIBMATTI_MC_PerlinNoise_GetValue(pb, 12.75, -30.5, 44.25);
        check(va == vb, "perlin seed determinism");
    }
    LIBMATTI_MC_PerlinNoise_Free(pa);
    LIBMATTI_MC_PerlinNoise_Free(pb);
}

// ---------------------------------------------------------------------------
// the flat generator end to end
// ---------------------------------------------------------------------------

static void test_flat_source(void)
{
    LIBMATTI_MC_Bootstrap_BootStrap();
    LIBMATTI_MC_Level *level = LIBMATTI_MC_Level_New(-64, 384, LIBMATTI_MC_Level_OVERWORLD, true);

    LIBMATTI_MC_Block *stone = LIBMATTI_MC_VanillaBlocks_GetByName("STONE");
    LIBMATTI_MC_Block *dirt = LIBMATTI_MC_VanillaBlocks_GetByName("DIRT");
    LIBMATTI_MC_Block *bedrock = LIBMATTI_MC_VanillaBlocks_GetByName("BEDROCK");
    LIBMATTI_MC_Block *air = LIBMATTI_MC_VanillaBlocks_AIR();
    check(stone != NULL && dirt != NULL && bedrock != NULL && air != NULL, "demo blocks registered");

    LIBMATTI_MC_FlatLayerInfo layers[3];
    LIBMATTI_MC_FlatLayerInfo_Init(&layers[0], 1, LIBMATTI_MC_Block_DefaultBlockState(bedrock));
    LIBMATTI_MC_FlatLayerInfo_Init(&layers[1], 2, LIBMATTI_MC_Block_DefaultBlockState(dirt));
    LIBMATTI_MC_FlatLayerInfo_Init(&layers[2], 126, LIBMATTI_MC_Block_DefaultBlockState(stone));
    LIBMATTI_MC_FlatLevelSource *source = LIBMATTI_MC_FlatLevelSource_New(layers, 3, LIBMATTI_MC_Biomes_Plains());
    check(source != NULL, "flat source create");

    LIBMATTI_MC_ChunkPos pos = {2, -1};
    LIBMATTI_MC_LevelChunk *chunk = LIBMATTI_MC_LevelChunk_New(level, &pos);
    check(chunk != NULL, "chunk create");

    LIBMATTI_MC_ChunkGenerator *generator = &source->base;
    LIBMATTI_MC_ChunkGenerator_FillFromNoise(generator, &chunk->base);

    // the recipe: bedrock at -64, dirt at -63/-62, stone up through 64 (129
    // blocks over the -64 base - the surface top block rides y 64, the air
    // starts at 65 and getSpawnHeight answers 65)
    LIBMATTI_MC_BlockPos p1 = {{5, -64, 7}};
    LIBMATTI_MC_BlockPos p2 = {{5, -63, 7}};
    LIBMATTI_MC_BlockPos p3 = {{5, -62, 7}};
    LIBMATTI_MC_BlockPos p4 = {{5, 63, 7}};
    LIBMATTI_MC_BlockPos p5 = {{5, 64, 7}};
    LIBMATTI_MC_BlockPos p6 = {{5, 65, 7}};
    check(LIBMATTI_MC_LevelChunk_GetBlockState(chunk, &p1) == LIBMATTI_MC_Block_DefaultBlockState(bedrock),
          "bedrock layer at minY");
    check(LIBMATTI_MC_LevelChunk_GetBlockState(chunk, &p2) == LIBMATTI_MC_Block_DefaultBlockState(dirt),
          "dirt layer above bedrock");
    check(LIBMATTI_MC_LevelChunk_GetBlockState(chunk, &p3) == LIBMATTI_MC_Block_DefaultBlockState(dirt),
          "dirt layer top");
    check(LIBMATTI_MC_LevelChunk_GetBlockState(chunk, &p4) == LIBMATTI_MC_Block_DefaultBlockState(stone),
          "stone below the surface");
    check(LIBMATTI_MC_LevelChunk_GetBlockState(chunk, &p5) == LIBMATTI_MC_Block_DefaultBlockState(stone),
          "stone surface at y 64");
    check(LIBMATTI_MC_LevelChunk_GetBlockState(chunk, &p6) == LIBMATTI_MC_Block_DefaultBlockState(air),
          "air above the surface");

    // the worldgen heightmaps answer the surface top
    LIBMATTI_MC_Heightmap *worldSurface =
        LIBMATTI_MC_ChunkAccess_GetOrCreateHeightmapUnprimed(&chunk->base, LIBMATTI_MC_Heightmap_WORLD_SURFACE_WG);
    LIBMATTI_MC_Heightmap *oceanFloor =
        LIBMATTI_MC_ChunkAccess_GetOrCreateHeightmapUnprimed(&chunk->base, LIBMATTI_MC_Heightmap_OCEAN_FLOOR_WG);
    check(LIBMATTI_MC_Heightmap_GetFirstAvailable(worldSurface, 5, 7) == 65, "WORLD_SURFACE_WG first available");
    check(LIBMATTI_MC_Heightmap_GetFirstAvailable(oceanFloor, 5, 7) == 65, "OCEAN_FLOOR_WG first available");

    // the base/spawn heights
    check(LIBMATTI_MC_ChunkGenerator_GetBaseHeight(generator, 5, 7, LIBMATTI_MC_Heightmap_WORLD_SURFACE,
                                                   &level->heightAccessor)
              == 65,
          "getBaseHeight");
    check(LIBMATTI_MC_ChunkGenerator_GetSpawnHeight(generator, &level->heightAccessor) == 65, "getSpawnHeight");

    // the biome pass fills every section through the source
    LIBMATTI_MC_ChunkGenerator_FillBiomes(generator, &chunk->base);
    check(LIBMATTI_MC_LevelChunkSection_GetBiome(chunk->base.sections[4]) == LIBMATTI_MC_Biomes_Plains(),
          "section biome plains");

    // the section counts survived the generator writes
    check(chunk->base.sections[4]->nonEmptyBlockCount == 4096, "surface section full");
    check(chunk->base.sections[0]->nonEmptyBlockCount == 4096, "bottom section full");

    // Java: the live heightmaps prime once the features are in (the FEATURES ->
    // heightmapsAfter step): all six primed types answer the first air layer
    // over the flat surface for every one of the 256 columns
    {
        static const LIBMATTI_MC_HeightmapTypes LIVE_TYPES[] = {
            LIBMATTI_MC_Heightmap_MOTION_BLOCKING,
            LIBMATTI_MC_Heightmap_MOTION_BLOCKING_NO_LEAVES,
            LIBMATTI_MC_Heightmap_OCEAN_FLOOR,
            LIBMATTI_MC_Heightmap_WORLD_SURFACE,
            LIBMATTI_MC_Heightmap_OCEAN_FLOOR_WG,
            LIBMATTI_MC_Heightmap_WORLD_SURFACE_WG,
        };
        LIBMATTI_MC_Heightmap_PrimeHeightmaps(&chunk->base, LIVE_TYPES,
                                              sizeof(LIVE_TYPES) / sizeof(LIVE_TYPES[0]));
        int wrong = 0;
        for (size_t t = 0; t < sizeof(LIVE_TYPES) / sizeof(LIVE_TYPES[0]); t++)
        {
            LIBMATTI_MC_Heightmap *map =
                LIBMATTI_MC_ChunkAccess_GetOrCreateHeightmapUnprimed(&chunk->base, LIVE_TYPES[t]);
            if (map == NULL)
            {
                wrong++;
                continue;
            }
            for (int x = 0; x < 16; x++)
                for (int z = 0; z < 16; z++)
                    if (LIBMATTI_MC_Heightmap_GetFirstAvailable(map, x, z) != 65)
                        wrong++;
        }
        check(wrong == 0, "all six primed heightmaps answer 65 over every column");
    }

    // the save roundtrip carries the biome through the palette
    LIBMATTI_MC_Level_SetChunk(level, chunk);
    LIBMATTI_MC_Nbt_CompoundTag *tag = LIBMATTI_MC_SerializableChunkData_Write(chunk);
    check(tag != NULL, "chunk serializes");
    if (tag != NULL)
    {
        LIBMATTI_MC_Level *level2 = LIBMATTI_MC_Level_New(-64, 384, LIBMATTI_MC_Level_OVERWORLD, true);
        LIBMATTI_MC_LevelChunk *loaded = LIBMATTI_MC_SerializableChunkData_Read(level2, tag);
        check(loaded != NULL, "chunk parses");
        if (loaded != NULL)
        {
            check(LIBMATTI_MC_LevelChunk_GetBlockState(loaded, &p4) == LIBMATTI_MC_Block_DefaultBlockState(stone),
                  "loaded surface state");
            check(LIBMATTI_MC_LevelChunkSection_GetBiome(loaded->base.sections[4]) == LIBMATTI_MC_Biomes_Plains(),
                  "loaded biome");
            LIBMATTI_MC_Heightmap *loadedMap =
                LIBMATTI_MC_ChunkAccess_GetOrCreateHeightmapUnprimed(&loaded->base, LIBMATTI_MC_Heightmap_WORLD_SURFACE_WG);
            check(LIBMATTI_MC_Heightmap_GetFirstAvailable(loadedMap, 5, 7) == 65, "loaded heightmap");
            LIBMATTI_MC_LevelChunk_Free(loaded);
        }
        LIBMATTI_MC_Level_Free(level2);
        LIBMATTI_MC_Nbt_Tag_Free((LIBMATTI_MC_Nbt_Tag *) tag);
    }

    LIBMATTI_MC_Level_Free(level);
    LIBMATTI_MC_FlatLevelSource_Free(source);
}

// ---------------------------------------------------------------------------
// the biome identity
// ---------------------------------------------------------------------------

static void test_biome_identity(void)
{
    LIBMATTI_MC_Biome *plains = LIBMATTI_MC_Biomes_Plains();
    LIBMATTI_MC_Biome *again = LIBMATTI_MC_Biome_Of("minecraft:plains");
    check(plains == again, "biome interning returns the same pointer");
    check(strcmp(LIBMATTI_MC_Biome_GetId(plains), "minecraft:plains") == 0, "plains id");
    LIBMATTI_MC_Biome *desert = LIBMATTI_MC_Biomes_Desert();
    check(!LIBMATTI_MC_Biome_Equals(plains, desert), "plains != desert");
    check(LIBMATTI_MC_Biome_Equals(NULL, NULL), "NULL equality tolerance");

    // the checkerboard samples the cycle through the floor-divided grid
    LIBMATTI_MC_Biome *grid[2] = {plains, desert};
    LIBMATTI_MC_BiomeSource checkerboard = LIBMATTI_MC_BiomeSource_Checkerboard(grid, 2, 2);
    check(LIBMATTI_MC_BiomeSource_GetBiome(&checkerboard, 0, 64, 0) == plains, "checkerboard origin");
    check(LIBMATTI_MC_BiomeSource_GetBiome(&checkerboard, 15, 64, 0) == desert, "checkerboard second cell");
    check(LIBMATTI_MC_BiomeSource_GetBiome(&checkerboard, -1, 64, -1) == plains,
          "checkerboard negative coords fold");
    LIBMATTI_MC_BiomeSource fixed = LIBMATTI_MC_BiomeSource_Fixed(plains);
    check(LIBMATTI_MC_BiomeSource_GetBiome(&fixed, -9999, 64, 9999) == plains, "fixed source constant");
}

int main(void)
{
    test_rng();
    test_noise();
    test_biome_identity();
    test_flat_source();
    printf("worldgen harness: %d/%d checks ok\n", checks - failures, checks);
    return failures != 0;
}
