#!/usr/bin/env bash
# Embeds the FML theme font (Monocraft.ttf) as a C byte array so the
# release binaries carry the font inside - the CI build machine's
# source path does not exist on a user's machine.
#
# Usage: embed_font.sh <Monocraft.ttf> <out.c> <out.h>

set -euo pipefail

SRC="$1"
OUT_C="$2"
OUT_H="$3"

SIZE=$(wc -c < "$SRC")

{
  echo "/* Generated by tools/embed_font.sh - do not edit. */"
  echo "#include \"libmatti/net/minecraft/client/EmbeddedFont.h\""
  echo
  echo "#include <stddef.h>"
  echo
  echo "const unsigned char LIBMATTI_MC_EmbeddedFont_Monocraft[] = {"
  od -An -v -tu1 "$SRC" | awk '{ for (i = 1; i <= NF; i++) printf "%s,", ($i == "0" ? "0" : $i) }'
  echo "};"
  echo "const size_t LIBMATTI_MC_EmbeddedFont_Monocraft_Size = ${SIZE};"
} > "$OUT_C"

{
  echo "/* Generated by tools/embed_font.sh - do not edit. */"
  echo "#ifndef MATTICRAFT_MC_EMBEDDEDFONT_H"
  echo "#define MATTICRAFT_MC_EMBEDDEDFONT_H"
  echo
  echo "#include <stddef.h>"
  echo
  echo "// The FML theme font (Monocraft.ttf), embedded so release binaries"
  echo "// do not depend on the build machine's source tree."
  echo "extern const unsigned char LIBMATTI_MC_EmbeddedFont_Monocraft[];"
  echo "extern const size_t LIBMATTI_MC_EmbeddedFont_Monocraft_Size;"
  echo
  echo "#endif"
} > "$OUT_H"

echo "embedded ${SIZE} bytes -> ${OUT_C}, ${OUT_H}"
